#!/usr/bin/bash
#
# teps: replaces spaces in file and directory names.
#
# Copyright (C) 2018-2020 Leonardo Santos <https://github.com/s4nt0sl30n4rd0/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# -------------------------------------------------------------------------
usage(){
cat << EOF
Usage:
     $(basename $0) [DIR]
     $(basename $0) [-h]

     Replaces spaces in file and directory names.

     Exchanges spaces for underscores in file and directory names
     recursively within the given directory, including itself.

Options:
     DIR Name, relative or absolute path of a directory.
     -h  Display this help and exit.

     If a name or path to a directory is not entered as a parameter, it
     will act within the current directory, without including it.

Exit Status:
     Returns 0 for success and 1 for failure.
EOF
}

[ "$1" = '-h' ] \
&& {
  usage
  exit 0
}

rename(){
  space=1

  while [ $space -ne 0 ]
  do
    find -print0 | xargs -0 rename.ul ' ' '_' * 2> /dev/null
    space=$(find -print0 | grep -c ' ')
  done
}

if [ -n "$1" ]
then
  target=$1

  cd "$target" \
  || {
    echo 'Error: file or directory not found.'
    exit 1
  }

  rename
  cd ..

  target=$(basename "$target")

  mv "$target" "${target// /_}"
else
  target=$PWD

  rename
fi
